import Head from "next/head";
import { WebFooter } from "~/components/footers/Web.footer";
import { WebHeader } from "~/components/headers/Web.header";

type WebLayoutProps = { title: string; children: JSX.Element | JSX.Element[] };
export function WebLayout({ title, children }: WebLayoutProps) {
    return (
        <>
            <Head>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <title>{title} - Eccomerce</title>
            </Head>
            <WebHeader />
            {children}
            <WebFooter />
        </>
    );
}
